import {build} from 'esbuild';
import {sassPlugin} from 'esbuild-sass-plugin';
import parser from 'yargs-parser';

const buildOptions = parser(process.argv.slice(2), {
  boolean: ['debug'],
});

build({
  entryPoints: [
    'client/formset-extensions.ts',
    'client/formset/GlyphSelector.ts',
  ],
  bundle: true,
  minify: !buildOptions.debug,
  sourcemap: buildOptions.debug,
  banner: {
    js: '// This file is generated by esbuild\n// !!!DO NOT EDIT!!!\n',
  },
  outdir: 'cmsplugin_cascade/static/cascade/admin/bootstrap5/js',
  plugins: [
    sassPlugin({type: 'style'}),
  ],
  loader: {},
  target: ['es2020', 'chrome84', 'firefox84', 'safari14', 'edge84']
});
