# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-19 14:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cmsplugin_cascade', '0006_bootstrapgallerypluginmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BootstrapAccordionPanelPluginModel',
        ),
        migrations.DeleteModel(
            name='BootstrapAccordionPluginModel',
        ),
        migrations.DeleteModel(
            name='BootstrapButtonPluginModel',
        ),
        migrations.DeleteModel(
            name='BootstrapColumnPluginModel',
        ),
        migrations.DeleteModel(
            name='BootstrapContainerPluginModel',
        ),
        migrations.DeleteModel(
            name='BootstrapGalleryPluginModel',
        ),
        migrations.DeleteModel(
            name='BootstrapImagePluginModel',
        ),
        migrations.DeleteModel(
            name='BootstrapPanelPluginModel',
        ),
        migrations.DeleteModel(
            name='BootstrapPicturePluginModel',
        ),
        migrations.DeleteModel(
            name='BootstrapPluginBaseModel',
        ),
        migrations.DeleteModel(
            name='BootstrapRowPluginModel',
        ),
        migrations.DeleteModel(
            name='BootstrapSecondaryMenuPluginModel',
        ),
        migrations.DeleteModel(
            name='BootstrapTabPanePluginModel',
        ),
        migrations.DeleteModel(
            name='BootstrapTabSetPluginModel',
        ),
        migrations.DeleteModel(
            name='CarouselPluginModel',
        ),
        migrations.DeleteModel(
            name='CarouselSlidePluginModel',
        ),
        migrations.CreateModel(
            name='HeadingPluginModel',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('cmsplugin_cascade.cascadeelement',),
        ),
        migrations.CreateModel(
            name='HorizontalRulePluginModel',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('cmsplugin_cascade.cascadeelement',),
        ),
        migrations.CreateModel(
            name='SimpleWrapperPluginModel',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('cmsplugin_cascade.cascadeelement',),
        ),
    ]
