# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-07 22:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0013_urlconfrevision'),
        ('cmsplugin_cascade', '0008_sortableinlinecascadeelement'),
    ]

    operations = [
        migrations.CreateModel(
            name='CascadePage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('settings', jsonfield.fields.JSONField(blank=True, default={}, help_text='User editable settings for this page.')),
                ('glossary', jsonfield.fields.JSONField(blank=True, default={}, help_text='Store for arbitrary page data.')),
                ('extended_object', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='cms.Page')),
                ('public_extension', models.OneToOneField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='draft_extension', to='cmsplugin_cascade.CascadePage')),
            ],
            options={
                'db_table': 'cmsplugin_cascade_page',
                'verbose_name': 'Cascade Page Settings',
                'verbose_name_plural': 'Cascade Page Settings',
            },
        ),
    ]
