# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-11 07:40
from __future__ import unicode_literals

from django.db import migrations

def forwards(apps, schema_editor):
    CascadeElement = apps.get_model('cmsplugin_cascade', 'CascadeElement')
    for element in CascadeElement.objects.filter(plugin_type='HeadingPlugin'):
        head_size = element.glossary.pop('head_size', None)
        if head_size:
            element.glossary['tag_type'] = 'h{}'.format(head_size)
            element.save()


class Migration(migrations.Migration):

    dependencies = [
        ('cmsplugin_cascade', '0009_cascadepage'),
    ]

    operations = [
        migrations.RunPython(forwards),
    ]
