# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-04 11:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cmsplugin_cascade', '0013_iconfont'),
        ('cmsplugin_cascade', '0012_auto_20160824_0959'),
    ]

    operations = [
    ]
