# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-01-11 20:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import filer.fields.file


class Migration(migrations.Migration):

    dependencies = [
        ('cmsplugin_cascade', '0014_glossary_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iconfont',
            name='identifier',
            field=models.CharField(help_text='A unique identifier to distinguish this icon font.', max_length=50, unique=True, verbose_name='Identifier'),
        ),
        migrations.AlterField(
            model_name='iconfont',
            name='zip_file',
            field=filer.fields.file.FilerFileField(help_text='Upload a zip file created on <a href="http://fontello.com/" target="_blank">Fontello</a> containing fonts.', on_delete=django.db.models.deletion.CASCADE, to='filer.File'),
        ),
    ]
