# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-26 12:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cmsplugin_cascade', '0020_page_icon_font'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cascadepage',
            options={'verbose_name': 'Cascade Page Settings', 'verbose_name_plural': 'Cascade Page Settings'},
        ),
    ]
