# Generated by Django 5.1.6 on 2025-06-24 12:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmsplugin_cascade', '0033_add_cascade_page_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cascadepagecontent',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='PageContentAnchor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(help_text='A unique identifier for this anchor, used in the URL to link to this position.', max_length=100, verbose_name='Identifier')),
                ('cms_plugin', models.OneToOneField(help_text='The CMS plugin this anchor is associated with.', on_delete=django.db.models.deletion.CASCADE, to='cms.cmsplugin')),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anchors', to='cmsplugin_cascade.cascadepagecontent')),
            ],
            options={
                'verbose_name': 'Page Content Anchor',
                'verbose_name_plural': 'Page Content Anchors',
                'db_table': 'cmsplugin_cascade_anchor',
            },
        ),
        migrations.AddConstraint(
            model_name='pagecontentanchor',
            constraint=models.UniqueConstraint(fields=('content', 'identifier'), name='unique_page_content_anchor'),
        ),
    ]
