# Generated by Django 5.2.12 on 2026-03-11 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cmsplugin_cascade', '0034_alter_cascadepagecontent_id_pagecontentanchor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='iconfont',
            name='zip_file',
        ),
    ]
