# Generated by Django 5.2.12 on 2026-04-08 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmsplugin_cascade', '0035_remove_iconfont_zip_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iconfont',
            name='config_data',
            field=models.JSONField(default=dict),
        ),
    ]
