# Generated by Django 5.2.12 on 2026-06-22 06:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0042_remove_placeholderreference_placeholder_ref_and_more"),
        ("cmsplugin_cascade", "0036_alter_iconfont_config_data"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pagecontentanchor",
            name="content",
        ),
        migrations.RemoveField(
            model_name="pagecontentanchor",
            name="cms_plugin",
        ),
        migrations.RemoveField(
            model_name="cascadepage",
            name="public_extension",
        ),
        migrations.CreateModel(
            name="PageAnchor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "identifier",
                    models.CharField(
                        help_text="A unique identifier for this anchor, used in the URL to link to this position.",
                        max_length=100,
                        verbose_name="Identifier",
                    ),
                ),
                (
                    "page_url",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="anchors",
                        to="cms.pageurl",
                    ),
                ),
            ],
            options={
                "verbose_name": "Page Anchor",
                "verbose_name_plural": "Page Anchors",
                "db_table": "cmsplugin_cascade_pageanchor",
            },
        ),
        migrations.DeleteModel(
            name="CascadePageContent",
        ),
        migrations.DeleteModel(
            name="PageContentAnchor",
        ),
        migrations.AddConstraint(
            model_name="pageanchor",
            constraint=models.UniqueConstraint(
                fields=("page_url", "identifier"), name="unique_page_anchor"
            ),
        ),
    ]
